config/routes.rb
# == Route Map
#
#                                Prefix Verb     URI Pattern                                                     Controller#Action
# user_google_oauth2_omniauth_authorize GET|POST /users/auth/google_oauth2(.:format)                             users/omniauth_callbacks#passthru
#  user_google_oauth2_omniauth_callback GET|POST /users/auth/google_oauth2/callback(.:format)                    users/omniauth_callbacks#google_oauth2
#                      new_user_session GET      /sign_in(.:format)                                              devise/sessions#new
#                  destroy_user_session GET      /sign_out(.:format)                                             devise/sessions#destroy
#           estimation_estimation_items GET      /estimations/:estimation_id/estimation_items(.:format)          estimation_items#index
#                                       POST     /estimations/:estimation_id/estimation_items(.:format)          estimation_items#create
#        new_estimation_estimation_item GET      /estimations/:estimation_id/estimation_items/new(.:format)      estimation_items#new
#       edit_estimation_estimation_item GET      /estimations/:estimation_id/estimation_items/:id/edit(.:format) estimation_items#edit
#            estimation_estimation_item GET      /estimations/:estimation_id/estimation_items/:id(.:format)      estimation_items#show
#                                       PATCH    /estimations/:estimation_id/estimation_items/:id(.:format)      estimation_items#update
#                                       PUT      /estimations/:estimation_id/estimation_items/:id(.:format)      estimation_items#update
#                                       DELETE   /estimations/:estimation_id/estimation_items/:id(.:format)      estimation_items#destroy
#                           estimations GET      /estimations(.:format)                                          estimations#index
#                                       POST     /estimations(.:format)                                          estimations#create
#                        new_estimation GET      /estimations/new(.:format)                                      estimations#new
#                       edit_estimation GET      /estimations/:id/edit(.:format)                                 estimations#edit
#                            estimation GET      /estimations/:id(.:format)                                      estimations#show
#                                       PATCH    /estimations/:id(.:format)                                      estimations#update
#                                       PUT      /estimations/:id(.:format)                                      estimations#update
#                                       DELETE   /estimations/:id(.:format)                                      estimations#destroy
#                                  root GET      /                                                               estimations#index

Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :estimations do
    resources :estimation_items
    resources :estimation_shares, only: [:index, :create, :destroy] do
      member do
        post :transfer_ownership
      end
    end
    member do
      post :rotate_share_token
      post :disable_share_token
    end
  end

  namespace :admin do
    root 'dashboard#index'
    resources :users, only: [:index] do
      member do
        post :ban
        post :unban
      end
    end
  end

  # Public read-only view (token-based, no auth required)
  # Must come AFTER resources :estimations so nested routes match first
  get 'estimations/:id/:share_token', to: 'estimations#public_show', as: :public_estimation

  root 'estimations#index'
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Admin - Buffer Estimator</title>

    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bulma@1.0.4/css/bulma.min.css', integrity: 'sha384-DCY3M8xLkMu6c9IKcKbe+jHKMjelnwC0p+SBaxfHxoBYZWdJF2X400UdBCgATtAB', crossorigin: 'anonymous', 'data-turbo-track' => 'reload' %>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.0/css/all.min.css', integrity: 'sha512-9xKTRVabjVeZmc+GUW8GgSmcREDunMM+Dt/GrzchfN8tkwHizc5RP4Ok/MXFFy5rIjJjzhndFScTceq5e6GvVQ==', crossorigin: 'anonymous', 'data-turbo-track' => 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track' => 'reload' %>
    <%= csrf_meta_tags %>
    <%= javascript_importmap_tags %>
  </head>
  <body data-env="<%= Rails.env %>" class="has-background-light">
    <nav class="navbar is-danger" role="navigation" aria-label="admin navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="<%= admin_root_path %>">
          <strong><i class="fa-solid fa-shield-halved"></i> Admin Panel</strong>
        </a>
      </div>

      <div class="navbar-menu">
        <div class="navbar-start">
          <%= link_to admin_root_path, class: "navbar-item #{controller_name == 'dashboard' ? 'is-active' : ''}" do %>
            <i class="fa-solid fa-chart-line"></i>&nbsp;Dashboard
          <% end %>
          <%= link_to admin_users_path, class: "navbar-item #{controller_name == 'users' ? 'is-active' : ''}" do %>
            <i class="fa-solid fa-users"></i>&nbsp;Users
          <% end %>
        </div>

        <div class="navbar-end">
          <div class="navbar-item">
            <%= link_to root_path, class: "button is-light is-small" do %>
              <i class="fa-solid fa-arrow-left"></i>&nbsp;Back to App
            <% end %>
          </div>
          <div class="navbar-item">
            <%= link_to destroy_user_session_path, class: "button is-light is-small" do %>
              <i class="fa-solid fa-right-from-bracket"></i>&nbsp;Sign Out
            <% end %>
          </div>
        </div>
      </div>
    </nav>

    <%= turbo_frame_tag "flash" do %>
      <%= render "shared/flash" %>
    <% end %>

    <section class="section">
      <div class="container">
        <%= yield %>
      </div>
    </section>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><%= page_title %></title>

    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bulma@1.0.4/css/bulma.min.css', integrity: 'sha384-DCY3M8xLkMu6c9IKcKbe+jHKMjelnwC0p+SBaxfHxoBYZWdJF2X400UdBCgATtAB', crossorigin: 'anonymous', 'data-turbo-track' => 'reload' %>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.0/css/all.min.css', integrity: 'sha512-9xKTRVabjVeZmc+GUW8GgSmcREDunMM+Dt/GrzchfN8tkwHizc5RP4Ok/MXFFy5rIjJjzhndFScTceq5e6GvVQ==', crossorigin: 'anonymous', 'data-turbo-track' => 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track' => 'reload' %>
    <%= csrf_meta_tags %>
    <%= javascript_importmap_tags %>
  </head>
  <body data-env="<%= Rails.env %>">
    <nav
      class="navbar is-dark"
      role="navigation"
      aria-label="main navigation"
      data-controller="navbar"
    >
      <div class="navbar-brand">
        <a class="navbar-item" href="/"><strong>Buffer estimator</strong></a>

        <% if user_signed_in? %>
          <a
            role="button"
            class="navbar-burger"
            aria-label="menu"
            aria-expanded="false"
            data-navbar-target="burger"
            data-action="click->navbar#toggle"
          >
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        <% end %>
      </div>

      <% if user_signed_in? %>
        <div class="navbar-menu" data-navbar-target="menu">
          <div class="navbar-end">
            <% if current_user.admin? %>
              <div class="navbar-item">
                <%= link_to admin_root_path, class: "button is-danger is-light" do %>
                  <span class="icon">
                    <i class="fa-solid fa-shield-halved"></i>
                  </span>
                  <span>Admin</span>
                <% end %>
              </div>
            <% end %>
            <div class="navbar-item">
              <%= link_to :destroy_user_session, class: "button is-light" do %>
                <span class="icon">
                  <i class="fa-solid fa-right-from-bracket"></i>
                </span>
                <span>Sign out</span>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </nav>

    <%= turbo_frame_tag "flash" do %>
      <%= render "shared/flash" %>
    <% end %>

    <div class="container"><%= yield %></div>
  </body>
</html>